### ISSUE TITLE
Trailing stop loss doesn't work

### ISSUE THREAD

**Issue by Yury-MonZon** [whittlem/pycryptobot#242]
**Describe the bug**
Trailing stop loss does not trigger

**To Reproduce**
python3 pycryptobot.py --market ETHUSDT --verbose 1 --disablebullonly --disablebuynearhigh --disablebuyobv --disablebuyelderray --sim fast --sellatloss 1 --trailingstoploss -0.1

**Expected behavior**
Trailing stop loss should trigger when current margin goes lower than max margin by 0.1% (in this example). I've tried different values too.

**Screenshots**
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release : v2.12.0                                              |
--------------------------------------------------------------------------------
|                Market : ETHUSDT                                              |
|           Granularity : 3600 seconds                                         |
--------------------------------------------------------------------------------
|              Bot Mode : TEST - test trades using dummy funds :)              |
|           Bot Started : 2021-05-25 18:49:50.815845                           |
================================================================================
|          Sell At Loss : True  --sellatloss True                              |
|    Sell At Resistance : False  --sellatresistance                            |
|       Trade Bull Only : False  --disablebullonly                             |
|         Buy Near High : False  --disablebuynearhigh                          |
|          Use Buy MACD : True  --disablebuymacd                               |
|           Use Buy OBV : False  --disablebuyobv                               |
|     Use Buy Elder-Ray : False  --disablebuyelderray                          |
|    Sell Fibonacci Low : True  --disablefailsafefibonaccilow                  |
|  Candlestick Reversal : True  --disableprofitbankreversal                    |
|              Telegram : True  --disabletelegram                              |
|                   Log : True  --disablelog                                   |
|               Tracker : True  --disabletracker                               |
|      Auto restart Bot : True  --autorestart                                  |
================================================================================

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version 2.12.0
 - Sim mode
 - Binance exchange

**Comment by whittlem** [comment]
This is fixed. It wasn't allowing a negative float and was being disabled by sellatloss. I updated it to allow a negative float as well as negative int and to still work if the margin is > 0.

**Comment by Yury-MonZon** [comment]
Something is not working as expected
python3 pycryptobot.py --market LTCUSDT --verbose 0 --disablebullonly --disablebuynearhigh --disablebuyobv --disablebuyelderray --sim fast --sellatloss 1 --trailingstoploss -0.1 --granularity 1h


2021-05-13 23:00:00 | LTCUSDT | 1h | Close: 317.9500 | BUY

 2021-05-13 23:00:00 | LTCUSDT 1h | Close: 317.9500 | BUY
 Fibonacci Retracement Levels: {'ratio0_286': 276.25, 'ratio0': 335.56}
 Support level of 184.15 formed at 2021-05-22 13:00:00 

* Candlestick Detected: Hammer ("Weak - Reversal - Bullish Signal - Up") 

* Candlestick Detected: Hammer ("Weak - Reversal - Bullish Signal - Up")
2021-05-14 00:00:00 | LTCUSDT | 1h | Close: 319.6100 |  ^ EMA12/26: 308.6972 > 306.6875 ^  | ^ MACD: 2.0097 > 0.5714 ^ | WAIT | Last Action: BUY | 0.3211% (delta: 1.66)
support: 297.48, resistance: 320.89, fibonacci (l): 276.25, fibonacci (u): 335.56
2021-05-14 01:00:00 | LTCUSDT | 1h | Close: 317.7700 |  ^ EMA12/26: 310.0930 > 307.5084 ^  | ^ MACD: 2.5846 > 0.9740 ^ | WAIT | Last Action: BUY | -0.2564% (delta: -0.18)
support: 297.48, resistance: 320.89, fibonacci (l): 276.25, fibonacci (u): 335.56
2021-05-14 02:00:00 | LTCUSDT | 1h | Close: 309.9700 |  ^ EMA12/26: 310.0741 > 307.6907 ^  | ^ MACD: 2.3833 > 1.2559 ^ | WAIT | Last Action: BUY | -2.7047% (delta: -7.98)
support: 297.48, resistance: 320.89, fibonacci (l): 276.25, fibonacci (u): 335.56
2021-05-14 03:00:00 | LTCUSDT | 1h | Close: 311.6100 |  ^ EMA12/26: 310.3103 > 307.9810 ^  | ^ MACD: 2.3293 > 1.4706 ^ | WAIT | Last Action: BUY | -2.1899% (delta: -6.34)
support: 297.48, resistance: 320.89, fibonacci (l): 276.25, fibonacci (u): 335.56
2021-05-14 04:00:00 | LTCUSDT | 1h | Close: 312.5500 |  ^ EMA12/26: 310.6549 > 308.3195 ^  | ^ MACD: 2.3354 > 1.6435 ^ | WAIT | Last Action: BUY | -1.8949% (delta: -5.4)
support: 297.48, resistance: 320.89, fibonacci (l): 276.25, fibonacci (u): 335.56
! Trailing Stop Loss Triggered (< -0.1%)

**Comment by iThom** [comment]
You are using old code regarding the date of your logs: 2021-05-142021-05-14
It was fixed in the commit 2ae05b77 with a margin > 0 so with -1.8949 it should not sell

**Comment by iThom** [comment]
@Yury-MonZon Still have the issue in simulations even after the last version of the bot including the commit 2ae05b7.

He asked me to reopen the issue (currently reporter can't reopen the issue, maybe it's a config in github for the project).

**Comment by iThom** [comment]
Issue #251 seems finally not fixed as well, but let's keep only this issue opened.

**Comment by aswinkp** [comment]
I pulled and ran once again in `live mode`, but selllowerpcnt: -5 got executed instead of trailingstoploss": -2 which is the reverse of what is documented in the medium article.. So I think selllowerpcnt is getting more priority than trailingstoploss.

**Comment by aswinkp** [comment]
I spent some time debugging the issue. and I noticed the if condition.  
`if margin > 0 and app.trailingStopLoss() != None and change_pcnt_high < app.trailingStopLoss():` 

I think `margin > 0` is where it goes wrong. In my case the buy order was executed, price went up by 1.5%, and then went down negative. While I was expecting trailingstoploss to sell by -0.5%, the margin > 0 stopped that if condition from executing. So the selllowerpercent for -5% got executed.

**Comment by aswinkp** [comment]
Another scenario while running it live. I have printed the margin percentage in the print statement to know what was going on. It is not just happening for negative values, but also for positive margins. 
```
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release : v2.13.5                                              |
--------------------------------------------------------------------------------
|              Bot Mode : LIVE - live trades using your funds!                 |
|           Bot Started : 2021-05-26 21:08:11.670648                           |
================================================================================
|        Sell Lower : -2.0%                                                    |
|        Trailing Stop Loss : -2.0%                                            |
|          Sell At Loss : True  --sellatloss True                              |
|    Sell At Resistance : False  --sellatresistance                            |
|       Trade Bull Only : False  --disablebullonly                             |
|         Buy Near High : True  --disablebuynearhigh                           |
|          Use Buy MACD : True  --disablebuymacd                               |
|           Use Buy OBV : False  --disablebuyobv                               |
|     Use Buy Elder-Ray : False  --disablebuyelderray                          |
|    Sell Fibonacci Low : True  --disablefailsafefibonaccilow                  |
|       Sell Lower Pcnt : True  --disablefailsafelowerpcnt                     |
|  Candlestick Reversal : True  --disableprofitbankreversal                    |
|              Telegram : True  --disabletelegram                              |
|                   Log : False  --disablelog                                  |
|               Tracker : True  --disabletracker                               |
|      Auto restart Bot : True  --autorestart                                  |
================================================================================

...
...
...
2021-05-26 22:26:06 | ANTBNB | 1h | Current Price: 0.01518 | Margin  14.85712188%
2021-05-26 22:28:09 | ANTBNB | 1h | Current Price: 0.01536 | Margin  16.21907489%
2021-05-26 22:32:15 | ANTBNB | 1h | Current Price: 0.0152 | Margin  15.00845815%
2021-05-26 22:34:18 | ANTBNB | 1h | Current Price: 0.01477 | Margin  11.75493392%
2021-05-26 22:36:20 | ANTBNB | 1h | Current Price: 0.01487 | Margin  12.51155653%
```

Hope this helps.

**Comment by whittlem** [comment]
I think removing that margin condition should fix this. Agreed?

**Comment by aswinkp** [comment]
@whittlem I tested already. Removing margin condition only fixes the solution for [this](https://github.com/whittlem/pycryptobot/issues/242#issuecomment-848811428) comment.

For [this](https://github.com/whittlem/pycryptobot/issues/242#issuecomment-849011034) this case we need to change `if state.last_buy_high > 1` to `if state.last_buy_high > 0` statement. Reason price of altcoins is never going to be more than 1. It will be always 0.001 or something like that. So buy high is never more than 1 and so `change_pcnt_high` remains 0 always.
